spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/sour_tea?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:sour_tea}
    password: ${DB_PASSWORD}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
